DesktopMobileSwitcher/Controllers/DVDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DesktopMobileSwitcher.Models;

namespace DesktopMobileSwitcher.Controllers {
    public class DVDController : Controller {
        private DVDContext db = new DVDContext();

        //
        // GET: /DVD/
        public ActionResult Index() {
            return View(db.DVDs.ToList());
        }

        //
        // GET: /DVD/Details/5
        public ActionResult Details(int id = 0) {
            DVD dvd = db.DVDs.Find(id);
            if (dvd == null) {
                return HttpNotFound();
            }
            return View(dvd);
        }

        //
        // GET: /DVD/Create
        public ActionResult Create() {
            return View();
        }

        //
        // POST: /DVD/Create
        [HttpPost]
        public ActionResult Create(DVD dvd) {
            if (ModelState.IsValid) {
                db.DVDs.Add(dvd);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dvd);
        }

        //
        // GET: /DVD/Edit/5
        public ActionResult Edit(int id = 0) {
            DVD dvd = db.DVDs.Find(id);
            if (dvd == null) {
                return HttpNotFound();
            }
            return View(dvd);
        }

        //
        // POST: /DVD/Edit/5
        [HttpPost]
        public ActionResult Edit(DVD dvd) {
            if (ModelState.IsValid) {
                db.Entry(dvd).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dvd);
        }

        //
        // GET: /DVD/Delete/5
        public ActionResult Delete(int id = 0) {
            DVD dvd = db.DVDs.Find(id);
            if (dvd == null) {
                return HttpNotFound();
            }
            return View(dvd);
        }

        //
        // POST: /DVD/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id) {
            DVD dvd = db.DVDs.Find(id);
            db.DVDs.Remove(dvd);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DesktopMobileSwitcher/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace DesktopMobileSwitcher.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

DesktopMobileSwitcher/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="b">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header" data-iconpos="left">
            <a href="@Url.Action("Index", "DVD")" data-icon="home">Home</a>
            <h1>@ViewBag.Title</h1>
            <a href="@Url.Action("Create", "DVD")" data-icon="plus">New</a>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>
    
    @RenderSection("scripts", required: false)
</body>
</html>

DesktopMobileSwitcher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                @Html.Partial("_ViewSwitcher")
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

DesktopMobileSwitcher/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}